{
  "swagger": "2.0",
  "info": {
    "title": "Movies API",
    "description": "Team 09 CSE341 Movies API",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "paths": {
    "/movies/": {
      "get": {
        "tags": [
          "Movies"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Movies"
        ],
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MoviePostInput"
            }
          }
        ],
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/movies/{id}": {
      "get": {
        "tags": [
          "Movies"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "tags": [
          "Movies"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MoviePutInput"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Movies"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/actors/": {
      "get": {
        "tags": [
          "Actors"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Actors"
        ],
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActorPostInput"
            }
          }
        ],
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/actors/{id}": {
      "get": {
        "tags": [
          "Actors"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "tags": [
          "Actors"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ActorPutInput"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Actors"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/directors/": {
      "get": {
        "tags": [
          "Directors"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Directors"
        ],
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DirectorPostInput"
            }
          }
        ],
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/directors/{id}": {
      "get": {
        "tags": [
          "Directors"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "tags": [
          "Directors"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DirectorPutInput"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Directors"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/users/": {
      "get": {
        "tags": [
          "Users"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "description": "",
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserPostInput"
            }
          }
        ],
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "description": "",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserPutInput"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "description": "",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Not Found"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "sessionAuth": []
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "sessionAuth": {
      "type": "apiKey",
      "in": "header",
      "name": "Cookie",
      "description": "Session-based auth. Login via /auth/github in the browser; Swagger requests use the session cookie automatically."
    }
  },
  "definitions": {
    "MoviePostInput": {
      "type": "object",
      "required": [
        "title",
        "releaseYear",
        "genre",
        "rating",
        "runtimeMinutes",
        "directorId",
        "actorIds",
        "synopsis"
      ],
      "properties": {
        "title": {
          "type": "string",
          "example": "The Dark Knight Rises"
        },
        "releaseYear": {
          "type": "integer",
          "example": 2012
        },
        "genre": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Action"
          ]
        },
        "rating": {
          "type": "string",
          "example": "PG-13"
        },
        "runtimeMinutes": {
          "type": "integer",
          "example": 165
        },
        "directorId": {
          "type": "string",
          "example": "67f0c3e0a1b2c3d4e5f60789"
        },
        "actorIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "67f0c3e0a1b2c3d4e5f60790",
            "67f0c3e0a1b2c3d4e5f60791"
          ]
        },
        "synopsis": {
          "type": "string",
          "example": "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace."
        }
      },
      "example": {
        "title": "The Dark Knight Rises",
        "releaseYear": 2012,
        "genre": [
          "Action"
        ],
        "rating": "PG-13",
        "runtimeMinutes": 165,
        "directorId": "67f0c3e0a1b2c3d4e5f60789",
        "actorIds": [
          "67f0c3e0a1b2c3d4e5f60790",
          "67f0c3e0a1b2c3d4e5f60791"
        ],
        "synopsis": "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace."
      }
    },
    "MoviePutInput": {
      "type": "object",
      "required": [
        "title",
        "releaseYear",
        "genre",
        "rating",
        "runtimeMinutes",
        "directorId",
        "actorIds",
        "synopsis"
      ],
      "properties": {
        "title": {
          "type": "string",
          "example": "The Dark Knight Rises"
        },
        "releaseYear": {
          "type": "integer",
          "example": 2012
        },
        "genre": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Action",
            "Crime"
          ]
        },
        "rating": {
          "type": "string",
          "example": "PG-13"
        },
        "runtimeMinutes": {
          "type": "integer",
          "example": 165
        },
        "directorId": {
          "type": "string",
          "example": "67f0c3e0a1b2c3d4e5f60789"
        },
        "actorIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "67f0c3e0a1b2c3d4e5f60790",
            "67f0c3e0a1b2c3d4e5f60791"
          ]
        },
        "synopsis": {
          "type": "string",
          "example": "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again."
        }
      },
      "example": {
        "title": "The Dark Knight Rises",
        "releaseYear": 2012,
        "genre": [
          "Action",
          "Crime"
        ],
        "rating": "PG-13",
        "runtimeMinutes": 165,
        "directorId": "67f0c3e0a1b2c3d4e5f60789",
        "actorIds": [
          "67f0c3e0a1b2c3d4e5f60790",
          "67f0c3e0a1b2c3d4e5f60791"
        ],
        "synopsis": "Bane, an imposing terrorist, attacks Gotham City and disrupts its eight-year-long period of peace. This forces Bruce Wayne to come out of hiding and don the cape and cowl of Batman again."
      }
    },
    "ActorPostInput": {
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "birthDate",
        "nationality",
        "awards"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "example": "Christian"
        },
        "lastName": {
          "type": "string",
          "example": "Bale"
        },
        "birthDate": {
          "type": "string",
          "format": "date",
          "example": "1975-01-30"
        },
        "nationality": {
          "type": "string",
          "example": "British"
        },
        "awards": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Academy Award"
          ]
        }
      },
      "example": {
        "firstName": "Christian",
        "lastName": "Bale",
        "birthDate": "1975-01-30",
        "nationality": "British",
        "awards": [
          "Academy Award"
        ]
      }
    },
    "ActorPutInput": {
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "birthDate",
        "nationality",
        "awards"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "example": "Christian"
        },
        "lastName": {
          "type": "string",
          "example": "Bale"
        },
        "birthDate": {
          "type": "string",
          "format": "date",
          "example": "1974-01-30"
        },
        "nationality": {
          "type": "string",
          "example": "British"
        },
        "awards": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Academy Award"
          ]
        }
      },
      "example": {
        "firstName": "Christian",
        "lastName": "Bale",
        "birthDate": "1974-01-30",
        "nationality": "British",
        "awards": [
          "Academy Award"
        ]
      }
    },
    "DirectorPostInput": {
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "birthDate",
        "nationality"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "example": "Robert"
        },
        "lastName": {
          "type": "string",
          "example": "Zemeckis"
        },
        "birthDate": {
          "type": "string",
          "format": "date",
          "example": "1950-05-14"
        },
        "nationality": {
          "type": "string",
          "example": "American"
        },
        "awards": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Academy Award Best Director"
          ]
        }
      },
      "example": {
        "firstName": "Robert",
        "lastName": "Zemeckis",
        "birthDate": "1950-05-14",
        "nationality": "American",
        "awards": [
          "Academy Award Best Director"
        ]
      }
    },
    "DirectorPutInput": {
      "type": "object",
      "required": [
        "firstName",
        "lastName",
        "birthDate",
        "nationality"
      ],
      "properties": {
        "firstName": {
          "type": "string",
          "example": "Robert"
        },
        "lastName": {
          "type": "string",
          "example": "Zemeckis"
        },
        "birthDate": {
          "type": "string",
          "format": "date",
          "example": "1951-05-14"
        },
        "nationality": {
          "type": "string",
          "example": "American"
        },
        "awards": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "example": [
            "Academy Award Best Director"
          ]
        }
      },
      "example": {
        "firstName": "Robert",
        "lastName": "Zemeckis",
        "birthDate": "1951-05-14",
        "nationality": "American",
        "awards": [
          "Academy Award Best Director"
        ]
      }
    },
    "UserPostInput": {
      "type": "object",
      "required": [
        "displayName",
        "role",
        "email"
      ],
      "properties": {
        "displayName": {
          "type": "string",
          "example": "John.Doe"
        },
        "role": {
          "type": "string",
          "example": "editor"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "john.doe@example.com"
        },
        "githubId": {
          "type": "string",
          "example": "12345"
        }
      },
      "example": {
        "displayName": "John.Doe",
        "role": "Doe",
        "email": "john.doe@example.com",
        "githubId": "12345"
      }
    },
    "UserPutInput": {
      "type": "object",
      "required": [
        "displayName",
        "role",
        "email"
      ],
      "properties": {
        "displayName": {
          "type": "string",
          "example": "John.Smith"
        },
        "role": {
          "type": "string",
          "example": "editor"
        },
        "email": {
          "type": "string",
          "format": "email",
          "example": "john.smith@example.com"
        },
        "githubId": {
          "type": "string",
          "example": "12345"
        }
      },
      "example": {
        "displayName": "John.Smith",
        "role": "editor",
        "email": "john.smith@example.com",
        "githubId": "12345"
      }
    }
  }
}